name: Trivy scan

on:
  workflow_dispatch:
jobs:
  
  build-images:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images
        working-directory: ./docker
        run: |
          docker compose build


  trivy-scan:
    runs-on: self-hosted
    needs: build-images
    strategy:
      matrix:
        image: 
          - wazuh/wazuh-manager:4.12.0
          - wazuh/wazuh-indexer:4.12.0
          - wazuh/wazuh-dashboard:4.12.0
          - nginx:latest
    steps:
      - name: Make report directory
        working-directory: ./testing
        run: |
          mkdir trivy-reports
      - name: Run Trivy scan
        working-directory: ./trivy-reports
        run: |
          IMAGE=${{ matrix.image }}
          REPORT_FILE="$(echo $IMAGE | tr / _ | tr : _).txt"
          echo "ðŸ” Scanning $IMAGE"
          trivy image --exit-code 0 --severity HIGH,CRITICAL -o $REPORT_FILE $IMAGE
          echo "artifactName=$REPORT_FILE" >> $GITHUB_ENV
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifactName }}
          path: trivy-reports/

       
